name: 'Setup job'
description: ''

runs:
  using: 'composite'
  steps:
    - name: Setup node
      uses: actions/setup-node@v4.4.0
      with:
        node-version: 20.10.0
        cache: yarn

    - name: Run yarn install
      shell: bash
      run: yarn --immutable
