nodeLinker: node-modules

packageExtensions:
  "@types/node@22.13.1":
    dependencies:
      undici-types: 6.20.0
  "@types/ssh2-sftp-client@9.0.4":
    dependencies:
      "@types/node": 22.13.1
  "@types/ssh2@1.15.4":
    dependencies:
      "@types/node": 22.13.1

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux
    - darwin

yarnPath: .yarn/releases/yarn-4.9.2.cjs
