nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.0.2.cjs

supportedArchitectures:
  os: [linux, darwin]
  cpu: [x64, arm64]

packageExtensions:
  "@types/ssh2-sftp-client@9.0.4":
    dependencies:
      "@types/node": "22.13.1"
  "@types/ssh2@1.15.4":
    dependencies:
      "@types/node": "22.13.1"
  "@types/node@22.13.1":
    dependencies:
      "undici-types": "6.20.0"
