version: '3'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'

  mysql:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_PORT: 3306

    ports:
      - '3306:3306'
