# Only use this for Angular packages that should have their own TypeScript installation
packages:
    - examples/node-modules-linking
#    - packages/api-console-gui
#    - packages/desktop-ui
#    - packages/framework-debug-gui
#    - packages/orm-browser-gui
#    - packages/ui-library
