name: Build Docker Images

on:
  push:
    branches: [master]
    paths:
      - '.github/docker/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-mongo-replica:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        mongo-version: ['4', '5', '6', '7']
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .github/docker/mongo-replica
          push: true
          build-args: |
            MONGO_VERSION=${{ matrix.mongo-version }}
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/mongo-replica:${{ matrix.mongo-version }}
