name: GJS
on:
  pull_request:
  push:

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install GJS
        run: sudo apt-get --yes install gjs
      - name: Install NPM dependencies
        run: npm ci
      - name: Bootstrap
        run: npm run bootstrap:ci
      - name: Link
        run: npm run link
      - name: Build Platform
        run: npm run build:platform
      - name: Install compiler
        run: npm run install-compiler
      - name: Test
        run: npm run lerna -- test:gjs --scope="@deepkit/platform"
