name: Node.js
on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      matrix:
        node-version: [ 16.x ]
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NPM dependencies
        run: npm ci
      - name: Bootstrap
        run: npm run bootstrap:ci
      - name: Link
        run: npm run link
      - name: Build Platform
        run: npm run build:platform
      - name: Install compiler
        run: npm run install-compiler
      - name: Test
        run: npm run lerna -- test:node --scope="@deepkit/platform"
