on:
    workflow_call:
        inputs:
            configuration:
                required: false
                type: string
            target:
                required: false
                type: string
                default: build
        outputs:
            projects:
                value: ${{ jobs.print-affected.outputs.projects }}

env:
    NX_CLOUD_ENCRYPTION_KEY: ${{ secrets.NX_CLOUD_ENCRYPTION_KEY }}
    NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
    NX_VERBOSE_LOGGING: ${{ secrets.NX_VERBOSE_LOGGING }}
    NX_SKIP_NX_CACHE: ${{ secrets.NX_SKIP_NX_CACHE }}
    NX_TASKS_RUNNER: ${{ secrets.NX_TASKS_RUNNER }}
    NX_PERF_LOGGING: ${{ secrets.NX_PERF_LOGGING }}

permissions:
    contents: read
    actions: read
    pull-requests: read
    id-token: write

jobs:
    print-affected:
        runs-on: ubuntu-latest
        outputs:
            projects: ${{ steps.print-affected.outputs.projects }}
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup
              id: setup
              uses: ./.github/actions/setup
              timeout-minutes: 10
            - name: Determine affected projects
              id: print-affected
              run: |
                  projects=$(pnpm nx print-affected -t=${{ inputs.target }} --configuration=${{ inputs.configuration }} --select=projects)
                  echo "projects=$projects" >> $GITHUB_OUTPUT
